/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../public/BeefRamenNoodles.glb 
*/

import React from "react";
import * as THREE from "three";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";
import EggMaterial from "./materials/EggMaterial";
import EggWhiteMaterial from "./materials/EggWhiteMaterial";
import NoodleMaterial from "./materials/NoodlesMaterial";
import BowlMaterial from "./materials/BowlMaterial";
const PRIMARY_LIGHT_POS = new THREE.Vector3(0.319, 7.495, -0.902);

function BeefRamenNoodles(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/BeefRamenNoodles.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="BezierCurve"
          position={[0.097, 2.741, -0.171]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group
          name="BezierCurve001"
          position={[0.039, 2.007, 0.332]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group
          name="Plane002"
          position={[2.655, 1.951, -8.174]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <group
          name="BezierCurve002"
          position={[2.657, 1.902, 0.787]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <group name="BezierCircle" position={[0, 8.034, 0]} scale={8.282}>
          <PerspectiveCamera
            name="Camera"
            makeDefault={false}
            far={100}
            near={0.1}
            fov={32.378}
            position={[0.515, -0.189, 0.465]}
            rotation={[-0.869, 0.62, 0.603]}
            scale={0.121}
          />
        </group>
        <pointLight
          name="Light"
          intensity={54351.413}
          decay={2}
          position={[0.319, 7.495, -0.902]}
          rotation={[-1.839, 0.602, 1.932]}
        />
        <mesh
          name="Circle"
          geometry={nodes.Circle.geometry}
          material={materials["Material.002"]}
          position={[0, 1.826, 0]}
        />
        <group
          name="Cube004"
          position={[0.722, 2.139, -1.129]}
          rotation={[0, 0, -0.122]}
        >
          <mesh
            name="Cube005_1"
            geometry={nodes.Cube005_1.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            name="Cube005_2"
            geometry={nodes.Cube005_2.geometry}
            material={materials["Material.008"]}
          />
        </group>
        <group
          name="Cube005"
          position={[1.369, 1.667, -0.592]}
          rotation={[-3.008, 0.22, 3.079]}
        >
          <mesh
            name="Cube006_1"
            geometry={nodes.Cube006_1.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            name="Cube006_2"
            geometry={nodes.Cube006_2.geometry}
            material={materials["Material.008"]}
          />
        </group>
        <group
          name="Cube006"
          position={[0.128, 1.828, -0.816]}
          rotation={[-Math.PI, 0.333, -Math.PI]}
        >
          <mesh
            name="Cube007_1"
            geometry={nodes.Cube007_1.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            name="Cube007_2"
            geometry={nodes.Cube007_2.geometry}
            material={materials["Material.013"]}
          />
        </group>
        <group
          name="Cube007"
          position={[-0.553, 1.697, -1.224]}
          rotation={[-Math.PI, -1.327, 3.02]}
        >
          <mesh
            name="Cube008_1"
            geometry={nodes.Cube008_1.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cube008_2"
            geometry={nodes.Cube008_2.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.009"]}
        >
          <BowlMaterial
            lightPosition={PRIMARY_LIGHT_POS}
            shininess={4.0} // Example: a higher value for a smaller, sharper highlight
          />
        </mesh>
        <mesh
          name="Cylinder001"
          geometry={nodes.Cylinder001.geometry}
          material={materials["Material.020"]}
          position={[0, 2.019, 0]}
          scale={[0.165, 0.051, 0.165]}
        />
        <mesh
          name="Cylinder002"
          geometry={nodes.Cylinder002.geometry}
          material={materials["Material.017"]}
          position={[0, 2.019, 0]}
          rotation={[0.122, 0.145, 0.108]}
          scale={[0.116, 0.051, 0.116]}
        />
        <mesh
          name="Cylinder003"
          geometry={nodes.Cylinder003.geometry}
          material={materials["Material.018"]}
          position={[0.495, 1.848, -0.127]}
          rotation={[-0.121, -0.116, -0.111]}
          scale={[0.116, 0.051, 0.116]}
        />
        <mesh
          name="Cylinder004"
          geometry={nodes.Cylinder004.geometry}
          material={materials["Material.020"]}
          position={[0.495, 1.848, -0.127]}
          rotation={[-0.455, -0.319, -0.424]}
          scale={[0.165, 0.051, 0.165]}
        />
        <mesh
          name="Cylinder005"
          geometry={nodes.Cylinder005.geometry}
          material={materials["Material.020"]}
          position={[-0.192, 1.918, 0.587]}
          rotation={[2.9, 0.944, -2.617]}
          scale={[0.165, 0.051, 0.165]}
        />
        <mesh
          name="Cylinder006"
          geometry={nodes.Cylinder006.geometry}
          material={materials["Material.021"]}
          position={[-0.192, 1.918, 0.587]}
          rotation={[0.317, -0.303, -2.934]}
          scale={[0.116, 0.051, 0.116]}
        />
        <mesh
          name="Cylinder007"
          geometry={nodes.Cylinder007.geometry}
          material={materials["Material.022"]}
          position={[1.325, 1.833, 1.037]}
          rotation={[3.02, -0.145, -3.033]}
          scale={[0.116, 0.051, 0.116]}
        />
        <mesh
          name="Cylinder008"
          geometry={nodes.Cylinder008.geometry}
          material={materials["Material.020"]}
          position={[1.325, 1.833, 1.037]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.165, 0.051, 0.165]}
        />
        <mesh
          name="Cylinder009"
          geometry={nodes.Cylinder009.geometry}
          material={materials["Material.024"]}
          position={[0.962, 1.828, 0.791]}
          rotation={[2.784, -0.957, -0.531]}
          scale={[0.165, 0.051, 0.165]}
        />
        <mesh
          name="Cylinder010"
          geometry={nodes.Cylinder010.geometry}
          material={materials["Material.025"]}
          position={[0.951, 1.783, 0.771]}
          rotation={[3.079, -0.865, -0.188]}
          scale={[0.116, 0.051, 0.116]}
        />
        <mesh
          name="Cylinder011"
          geometry={nodes.Cylinder011.geometry}
          material={materials["Material.026"]}
          position={[1.297, 1.808, 0.433]}
          rotation={[-3.134, -0.932, -0.245]}
          scale={[0.116, 0.051, 0.116]}
        />
        <mesh
          name="Cylinder012"
          geometry={nodes.Cylinder012.geometry}
          material={materials["Material.024"]}
          position={[1.297, 1.808, 0.433]}
          rotation={[-0.723, -0.697, 2.031]}
          scale={[0.165, 0.051, 0.165]}
        />
        <mesh
          name="Cylinder013"
          geometry={nodes.Cylinder013.geometry}
          material={materials["Material.024"]}
          position={[0.219, 1.861, 0.748]}
          rotation={[1.4, 0.898, 1.685]}
          scale={[0.165, 0.051, 0.165]}
        />
        <mesh
          name="Cylinder014"
          geometry={nodes.Cylinder014.geometry}
          material={materials["Material.027"]}
          position={[0.219, 1.861, 0.748]}
          rotation={[0.755, 0.998, 2.456]}
          scale={[0.116, 0.051, 0.116]}
        />
        <mesh
          name="Cylinder015"
          geometry={nodes.Cylinder015.geometry}
          material={materials["Material.028"]}
          position={[0.774, 1.876, 0.365]}
          rotation={[0.226, 0.836, 3.104]}
          scale={[0.116, 0.051, 0.116]}
        />
        <mesh
          name="Cylinder016"
          geometry={nodes.Cylinder016.geometry}
          material={materials["Material.024"]}
          position={[0.774, 1.876, 0.365]}
          rotation={[0.47, 0.948, 2.796]}
          scale={[0.165, 0.051, 0.165]}
        />
        <mesh
          name="Cylinder020"
          geometry={nodes.Cylinder020.geometry}
          material={materials["Material.029"]}
          position={[0.132, 1.798, 1.359]}
          rotation={[1.215, 1.051, -1.455]}
          scale={[0.165, 0.051, 0.165]}
        >
          <mesh
            name="Cylinder019"
            geometry={nodes.Cylinder019.geometry}
            material={materials["Material.031"]}
            rotation={[-0.91, 0.707, -0.224]}
            scale={[1.229, 0.666, 1.529]}
          />
        </mesh>
        <mesh
          name="Cylinder021"
          geometry={nodes.Cylinder021.geometry}
          material={materials["Material.029"]}
          position={[-0.552, 1.848, 0.365]}
          rotation={[-0.771, 0.928, 0.389]}
          scale={[0.165, 0.051, 0.165]}
        >
          <mesh
            name="Cylinder022"
            geometry={nodes.Cylinder022.geometry}
            material={materials["Material.032"]}
            rotation={[0.331, 0.308, 0.359]}
            scale={[0.908, 0.944, 0.851]}
          />
        </mesh>
        <mesh
          name="Cylinder024"
          geometry={nodes.Cylinder024.geometry}
          material={materials["Material.029"]}
          position={[-0.496, 1.848, 0.873]}
          rotation={[0, 1.43, 0]}
          scale={[0.165, 0.051, 0.165]}
        >
          <mesh
            name="Cylinder023"
            geometry={nodes.Cylinder023.geometry}
            material={materials["Material.033"]}
            rotation={[0.196, 0.153, 0.197]}
            scale={[0.755, 0.986, 0.751]}
          />
        </mesh>
        <group
          name="Sphere"
          position={[-1.14, 3.085, 0.037]}
          scale={[0.612, 0.224, 0.612]}
        >
          <mesh
            name="Sphere_1"
            geometry={nodes.Sphere_1.geometry}
            material={materials["Material.034"]}
          >
            <EggMaterial
              lightPosition={PRIMARY_LIGHT_POS}
              shininess={4.0} // Example: a higher value for a smaller, sharper highlight
            />
          </mesh>
          <mesh
            name="Sphere_2"
            geometry={nodes.Sphere_2.geometry}
            material={materials["Material.035"]}
          >
            <EggWhiteMaterial
              lightPosition={PRIMARY_LIGHT_POS}
              shininess={4.0} // Example: a higher value for a smaller, sharper highlight
            />
          </mesh>
        </group>
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["Material.011"]}
          position={[0.1, 1.861, 12.543]}
        >
          <NoodleMaterial
            lightPosition={PRIMARY_LIGHT_POS}
            shininess={4.0} // Example: a higher value for a smaller, sharper highlight
          />
        </mesh>
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={materials["Material.016"]}
          position={[0.041, 2.056, 9.903]}
        >
          <NoodleMaterial
            lightPosition={PRIMARY_LIGHT_POS}
            shininess={4.0} // Example: a higher value for a smaller, sharper highlight
          />
        </mesh>
        <mesh
          name="Cylinder017"
          geometry={nodes.Cylinder017.geometry}
          material={materials["Material.023"]}
          position={[-0.044, 1.833, 1.83]}
          scale={[0.165, 0.051, 0.165]}
        />
        <mesh
          name="Cylinder018"
          geometry={nodes.Cylinder018.geometry}
          material={materials["Material.036"]}
          position={[-0.044, 1.833, 1.83]}
          rotation={[0.122, 0.145, 0.108]}
          scale={[0.116, 0.051, 0.116]}
        />
        <mesh
          name="Cylinder025"
          geometry={nodes.Cylinder025.geometry}
          material={materials["Material.037"]}
          position={[0.651, 1.734, 1.112]}
          rotation={[1.976, -0.211, 2.111]}
          scale={[0.165, 0.051, 0.165]}
        />
        <group
          name="Cube008"
          position={[-0.85, 1.655, -1.489]}
          rotation={[0.005, 0.532, -0.245]}
        >
          <mesh
            name="Cube001"
            geometry={nodes.Cube001.geometry}
            material={materials["Material.038"]}
          />
          <mesh
            name="Cube001_1"
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.039"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/BeefRamenNoodles.glb");

export default BeefRamenNoodles;
