/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../public/Glasses.glb 
*/

import React from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import BowlMaterial from "./materials/BowlMaterial";
const PRIMARY_LIGHT_POS = new THREE.Vector3(0.319, 7.495, -0.902);
const MODEL_PATH = `${import.meta.env.BASE_URL}Glasses.glb`;
function Glasses(props) {
  const { nodes, materials } = useGLTF(MODEL_PATH);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane002.geometry}
        position={[-3.305, 0, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={-1}
      >
        <BowlMaterial
          lightPosition={PRIMARY_LIGHT_POS}
          shininess={4.0} // Example: a higher value for a smaller, sharper highlight
        />
      </mesh>
    </group>
  );
}

useGLTF.preload(MODEL_PATH);

export default Glasses;
